namespace HindIndisk.Api.Application.DTOs.Location;

public record BranchDto(
    long    Id,
    string  Name,
    string  Address,
    string? AddressLine2,
    string  City,
    string  PostalCode,
    string  Phone,
    string  Email,
    string  GoogleMapsLink,
    string  WeekdayHours,
    string  WeekendHours,
    string  WeekdayOpen,
    string  WeekdayClose,
    string  WeekendOpen,
    string  WeekendClose,
    string  ImageUrl,
    decimal Rating,
    int     ReviewCount,
    decimal DeliveryFee,
    bool    DeliveryFeeEnabled,
    bool    IsCloseOrder,
    string? CloseOrderNote,
    bool    IsCloseReservation,
    string? CloseReservationNote,
    bool    IsCloseDelivery,
    string? CloseDeliveryNote,
    bool    IsClosePickup,
    string? ClosePickupNote,
    int     MaxAdvanceDays
);
