namespace HindIndisk.Api.Application.DTOs.Admin;

public record AdminBranchDto(
    long    Id,
    string  Name,
    string  AddressLine1,
    string? AddressLine2,
    string  City,
    string  PostalCode,
    string  Country,
    string  Phone,
    string  Email,
    string  GoogleMapsLink,
    string  ImageUrl,
    decimal Rating,
    int     ReviewCount,
    decimal DeliveryFee,
    bool    DeliveryFeeEnabled,
    bool    IsCloseOrder,
    string? CloseOrderNote,
    string? CloseOrderNoteDa,
    bool    IsCloseReservation,
    string? CloseReservationNote,
    string? CloseReservationNoteDa,
    bool    IsCloseDelivery,
    string? CloseDeliveryNote,
    string? CloseDeliveryNoteDa,
    bool    IsClosePickup,
    string? ClosePickupNote,
    string? ClosePickupNoteDa,
    int     MaxAdvanceDays
);
