/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as OrderTrackingRouteImport } from './routes/order-tracking'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as MenuNameRouteImport } from './routes/menu.$name'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOrderStatusesRouteImport } from './routes/admin.order-statuses'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminExceptionLogsRouteImport } from './routes/admin.exception-logs'
import { Route as AdminEmailSettingsRouteImport } from './routes/admin.email-settings'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AccountReservationsRouteImport } from './routes/account.reservations'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AdminMenusIndexRouteImport } from './routes/admin.menus.index'
import { Route as AdminMenuIndexRouteImport } from './routes/admin.menu.index'
import { Route as AdminBranchesIndexRouteImport } from './routes/admin.branches.index'
import { Route as AdminWebsiteHomepageRouteImport } from './routes/admin.website.Homepage'
import { Route as AdminWebsiteGalleryRouteImport } from './routes/admin.website.Gallery'
import { Route as AdminWebsiteFooterRouteImport } from './routes/admin.website.Footer'
import { Route as AdminWebsiteAboutRouteImport } from './routes/admin.website.About'
import { Route as AdminMenusNewRouteImport } from './routes/admin.menus.new'
import { Route as AdminMenusMenuIdRouteImport } from './routes/admin.menus.$menuId'
import { Route as AdminMenuNewRouteImport } from './routes/admin.menu.new'
import { Route as AdminMenuItemIdRouteImport } from './routes/admin.menu.$itemId'
import { Route as AdminBranchesNewRouteImport } from './routes/admin.branches.new'
import { Route as AdminBranchesBranchIdRouteImport } from './routes/admin.branches.$branchId'

const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTrackingRoute = OrderTrackingRouteImport.update({
  id: '/order-tracking',
  path: '/order-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const MenuNameRoute = MenuNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => MenuRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrderStatusesRoute = AdminOrderStatusesRouteImport.update({
  id: '/order-statuses',
  path: '/order-statuses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExceptionLogsRoute = AdminExceptionLogsRouteImport.update({
  id: '/exception-logs',
  path: '/exception-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailSettingsRoute = AdminEmailSettingsRouteImport.update({
  id: '/email-settings',
  path: '/email-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AccountReservationsRoute = AccountReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AdminMenusIndexRoute = AdminMenusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMenusRoute,
} as any)
const AdminMenuIndexRoute = AdminMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMenuRoute,
} as any)
const AdminBranchesIndexRoute = AdminBranchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBranchesRoute,
} as any)
const AdminWebsiteHomepageRoute = AdminWebsiteHomepageRouteImport.update({
  id: '/Homepage',
  path: '/Homepage',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteGalleryRoute = AdminWebsiteGalleryRouteImport.update({
  id: '/Gallery',
  path: '/Gallery',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteFooterRoute = AdminWebsiteFooterRouteImport.update({
  id: '/Footer',
  path: '/Footer',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteAboutRoute = AdminWebsiteAboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminMenusNewRoute = AdminMenusNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMenusRoute,
} as any)
const AdminMenusMenuIdRoute = AdminMenusMenuIdRouteImport.update({
  id: '/$menuId',
  path: '/$menuId',
  getParentRoute: () => AdminMenusRoute,
} as any)
const AdminMenuNewRoute = AdminMenuNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMenuRoute,
} as any)
const AdminMenuItemIdRoute = AdminMenuItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AdminMenuRoute,
} as any)
const AdminBranchesNewRoute = AdminBranchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBranchesRoute,
} as any)
const AdminBranchesBranchIdRoute = AdminBranchesBranchIdRouteImport.update({
  id: '/$branchId',
  path: '/$branchId',
  getParentRoute: () => AdminBranchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/menu': typeof MenuRouteWithChildren
  '/offers': typeof OffersRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/reservation': typeof ReservationRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/branches': typeof AdminBranchesRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/email-settings': typeof AdminEmailSettingsRoute
  '/admin/exception-logs': typeof AdminExceptionLogsRoute
  '/admin/menu': typeof AdminMenuRouteWithChildren
  '/admin/menus': typeof AdminMenusRouteWithChildren
  '/admin/order-statuses': typeof AdminOrderStatusesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/menu/$name': typeof MenuNameRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/branches/new': typeof AdminBranchesNewRoute
  '/admin/menu/$itemId': typeof AdminMenuItemIdRoute
  '/admin/menu/new': typeof AdminMenuNewRoute
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/menus/new': typeof AdminMenusNewRoute
  '/admin/website/About': typeof AdminWebsiteAboutRoute
  '/admin/website/Footer': typeof AdminWebsiteFooterRoute
  '/admin/website/Gallery': typeof AdminWebsiteGalleryRoute
  '/admin/website/Homepage': typeof AdminWebsiteHomepageRoute
  '/admin/branches/': typeof AdminBranchesIndexRoute
  '/admin/menu/': typeof AdminMenuIndexRoute
  '/admin/menus/': typeof AdminMenusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/offers': typeof OffersRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/reservation': typeof ReservationRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/email-settings': typeof AdminEmailSettingsRoute
  '/admin/exception-logs': typeof AdminExceptionLogsRoute
  '/admin/order-statuses': typeof AdminOrderStatusesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/menu/$name': typeof MenuNameRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/menu': typeof MenuIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/branches/new': typeof AdminBranchesNewRoute
  '/admin/menu/$itemId': typeof AdminMenuItemIdRoute
  '/admin/menu/new': typeof AdminMenuNewRoute
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/menus/new': typeof AdminMenusNewRoute
  '/admin/website/About': typeof AdminWebsiteAboutRoute
  '/admin/website/Footer': typeof AdminWebsiteFooterRoute
  '/admin/website/Gallery': typeof AdminWebsiteGalleryRoute
  '/admin/website/Homepage': typeof AdminWebsiteHomepageRoute
  '/admin/branches': typeof AdminBranchesIndexRoute
  '/admin/menu': typeof AdminMenuIndexRoute
  '/admin/menus': typeof AdminMenusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/menu': typeof MenuRouteWithChildren
  '/offers': typeof OffersRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/reservation': typeof ReservationRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/branches': typeof AdminBranchesRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/email-settings': typeof AdminEmailSettingsRoute
  '/admin/exception-logs': typeof AdminExceptionLogsRoute
  '/admin/menu': typeof AdminMenuRouteWithChildren
  '/admin/menus': typeof AdminMenusRouteWithChildren
  '/admin/order-statuses': typeof AdminOrderStatusesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/menu/$name': typeof MenuNameRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/branches/new': typeof AdminBranchesNewRoute
  '/admin/menu/$itemId': typeof AdminMenuItemIdRoute
  '/admin/menu/new': typeof AdminMenuNewRoute
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/menus/new': typeof AdminMenusNewRoute
  '/admin/website/About': typeof AdminWebsiteAboutRoute
  '/admin/website/Footer': typeof AdminWebsiteFooterRoute
  '/admin/website/Gallery': typeof AdminWebsiteGalleryRoute
  '/admin/website/Homepage': typeof AdminWebsiteHomepageRoute
  '/admin/branches/': typeof AdminBranchesIndexRoute
  '/admin/menu/': typeof AdminMenuIndexRoute
  '/admin/menus/': typeof AdminMenusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/locations'
    | '/menu'
    | '/offers'
    | '/order-tracking'
    | '/reservation'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/email-settings'
    | '/admin/exception-logs'
    | '/admin/menu'
    | '/admin/menus'
    | '/admin/order-statuses'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/website'
    | '/menu/$name'
    | '/account/'
    | '/admin/'
    | '/menu/'
    | '/admin/branches/$branchId'
    | '/admin/branches/new'
    | '/admin/menu/$itemId'
    | '/admin/menu/new'
    | '/admin/menus/$menuId'
    | '/admin/menus/new'
    | '/admin/website/About'
    | '/admin/website/Footer'
    | '/admin/website/Gallery'
    | '/admin/website/Homepage'
    | '/admin/branches/'
    | '/admin/menu/'
    | '/admin/menus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/locations'
    | '/offers'
    | '/order-tracking'
    | '/reservation'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/customers'
    | '/admin/email-settings'
    | '/admin/exception-logs'
    | '/admin/order-statuses'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/website'
    | '/menu/$name'
    | '/account'
    | '/admin'
    | '/menu'
    | '/admin/branches/$branchId'
    | '/admin/branches/new'
    | '/admin/menu/$itemId'
    | '/admin/menu/new'
    | '/admin/menus/$menuId'
    | '/admin/menus/new'
    | '/admin/website/About'
    | '/admin/website/Footer'
    | '/admin/website/Gallery'
    | '/admin/website/Homepage'
    | '/admin/branches'
    | '/admin/menu'
    | '/admin/menus'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/locations'
    | '/menu'
    | '/offers'
    | '/order-tracking'
    | '/reservation'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/email-settings'
    | '/admin/exception-logs'
    | '/admin/menu'
    | '/admin/menus'
    | '/admin/order-statuses'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/website'
    | '/menu/$name'
    | '/account/'
    | '/admin/'
    | '/menu/'
    | '/admin/branches/$branchId'
    | '/admin/branches/new'
    | '/admin/menu/$itemId'
    | '/admin/menu/new'
    | '/admin/menus/$menuId'
    | '/admin/menus/new'
    | '/admin/website/About'
    | '/admin/website/Footer'
    | '/admin/website/Gallery'
    | '/admin/website/Homepage'
    | '/admin/branches/'
    | '/admin/menu/'
    | '/admin/menus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LocationsRoute: typeof LocationsRoute
  MenuRoute: typeof MenuRouteWithChildren
  OffersRoute: typeof OffersRoute
  OrderTrackingRoute: typeof OrderTrackingRoute
  ReservationRoute: typeof ReservationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-tracking': {
      id: '/order-tracking'
      path: '/order-tracking'
      fullPath: '/order-tracking'
      preLoaderRoute: typeof OrderTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/menu/$name': {
      id: '/menu/$name'
      path: '/$name'
      fullPath: '/menu/$name'
      preLoaderRoute: typeof MenuNameRouteImport
      parentRoute: typeof MenuRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order-statuses': {
      id: '/admin/order-statuses'
      path: '/order-statuses'
      fullPath: '/admin/order-statuses'
      preLoaderRoute: typeof AdminOrderStatusesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exception-logs': {
      id: '/admin/exception-logs'
      path: '/exception-logs'
      fullPath: '/admin/exception-logs'
      preLoaderRoute: typeof AdminExceptionLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-settings': {
      id: '/admin/email-settings'
      path: '/email-settings'
      fullPath: '/admin/email-settings'
      preLoaderRoute: typeof AdminEmailSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/reservations': {
      id: '/account/reservations'
      path: '/reservations'
      fullPath: '/account/reservations'
      preLoaderRoute: typeof AccountReservationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/menus/': {
      id: '/admin/menus/'
      path: '/'
      fullPath: '/admin/menus/'
      preLoaderRoute: typeof AdminMenusIndexRouteImport
      parentRoute: typeof AdminMenusRoute
    }
    '/admin/menu/': {
      id: '/admin/menu/'
      path: '/'
      fullPath: '/admin/menu/'
      preLoaderRoute: typeof AdminMenuIndexRouteImport
      parentRoute: typeof AdminMenuRoute
    }
    '/admin/branches/': {
      id: '/admin/branches/'
      path: '/'
      fullPath: '/admin/branches/'
      preLoaderRoute: typeof AdminBranchesIndexRouteImport
      parentRoute: typeof AdminBranchesRoute
    }
    '/admin/website/Homepage': {
      id: '/admin/website/Homepage'
      path: '/Homepage'
      fullPath: '/admin/website/Homepage'
      preLoaderRoute: typeof AdminWebsiteHomepageRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/Gallery': {
      id: '/admin/website/Gallery'
      path: '/Gallery'
      fullPath: '/admin/website/Gallery'
      preLoaderRoute: typeof AdminWebsiteGalleryRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/Footer': {
      id: '/admin/website/Footer'
      path: '/Footer'
      fullPath: '/admin/website/Footer'
      preLoaderRoute: typeof AdminWebsiteFooterRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/About': {
      id: '/admin/website/About'
      path: '/About'
      fullPath: '/admin/website/About'
      preLoaderRoute: typeof AdminWebsiteAboutRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/menus/new': {
      id: '/admin/menus/new'
      path: '/new'
      fullPath: '/admin/menus/new'
      preLoaderRoute: typeof AdminMenusNewRouteImport
      parentRoute: typeof AdminMenusRoute
    }
    '/admin/menus/$menuId': {
      id: '/admin/menus/$menuId'
      path: '/$menuId'
      fullPath: '/admin/menus/$menuId'
      preLoaderRoute: typeof AdminMenusMenuIdRouteImport
      parentRoute: typeof AdminMenusRoute
    }
    '/admin/menu/new': {
      id: '/admin/menu/new'
      path: '/new'
      fullPath: '/admin/menu/new'
      preLoaderRoute: typeof AdminMenuNewRouteImport
      parentRoute: typeof AdminMenuRoute
    }
    '/admin/menu/$itemId': {
      id: '/admin/menu/$itemId'
      path: '/$itemId'
      fullPath: '/admin/menu/$itemId'
      preLoaderRoute: typeof AdminMenuItemIdRouteImport
      parentRoute: typeof AdminMenuRoute
    }
    '/admin/branches/new': {
      id: '/admin/branches/new'
      path: '/new'
      fullPath: '/admin/branches/new'
      preLoaderRoute: typeof AdminBranchesNewRouteImport
      parentRoute: typeof AdminBranchesRoute
    }
    '/admin/branches/$branchId': {
      id: '/admin/branches/$branchId'
      path: '/$branchId'
      fullPath: '/admin/branches/$branchId'
      preLoaderRoute: typeof AdminBranchesBranchIdRouteImport
      parentRoute: typeof AdminBranchesRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReservationsRoute: typeof AccountReservationsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReservationsRoute: AccountReservationsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminBranchesRouteChildren {
  AdminBranchesBranchIdRoute: typeof AdminBranchesBranchIdRoute
  AdminBranchesNewRoute: typeof AdminBranchesNewRoute
  AdminBranchesIndexRoute: typeof AdminBranchesIndexRoute
}

const AdminBranchesRouteChildren: AdminBranchesRouteChildren = {
  AdminBranchesBranchIdRoute: AdminBranchesBranchIdRoute,
  AdminBranchesNewRoute: AdminBranchesNewRoute,
  AdminBranchesIndexRoute: AdminBranchesIndexRoute,
}

const AdminBranchesRouteWithChildren = AdminBranchesRoute._addFileChildren(
  AdminBranchesRouteChildren,
)

interface AdminMenuRouteChildren {
  AdminMenuItemIdRoute: typeof AdminMenuItemIdRoute
  AdminMenuNewRoute: typeof AdminMenuNewRoute
  AdminMenuIndexRoute: typeof AdminMenuIndexRoute
}

const AdminMenuRouteChildren: AdminMenuRouteChildren = {
  AdminMenuItemIdRoute: AdminMenuItemIdRoute,
  AdminMenuNewRoute: AdminMenuNewRoute,
  AdminMenuIndexRoute: AdminMenuIndexRoute,
}

const AdminMenuRouteWithChildren = AdminMenuRoute._addFileChildren(
  AdminMenuRouteChildren,
)

interface AdminMenusRouteChildren {
  AdminMenusMenuIdRoute: typeof AdminMenusMenuIdRoute
  AdminMenusNewRoute: typeof AdminMenusNewRoute
  AdminMenusIndexRoute: typeof AdminMenusIndexRoute
}

const AdminMenusRouteChildren: AdminMenusRouteChildren = {
  AdminMenusMenuIdRoute: AdminMenusMenuIdRoute,
  AdminMenusNewRoute: AdminMenusNewRoute,
  AdminMenusIndexRoute: AdminMenusIndexRoute,
}

const AdminMenusRouteWithChildren = AdminMenusRoute._addFileChildren(
  AdminMenusRouteChildren,
)

interface AdminWebsiteRouteChildren {
  AdminWebsiteAboutRoute: typeof AdminWebsiteAboutRoute
  AdminWebsiteFooterRoute: typeof AdminWebsiteFooterRoute
  AdminWebsiteGalleryRoute: typeof AdminWebsiteGalleryRoute
  AdminWebsiteHomepageRoute: typeof AdminWebsiteHomepageRoute
}

const AdminWebsiteRouteChildren: AdminWebsiteRouteChildren = {
  AdminWebsiteAboutRoute: AdminWebsiteAboutRoute,
  AdminWebsiteFooterRoute: AdminWebsiteFooterRoute,
  AdminWebsiteGalleryRoute: AdminWebsiteGalleryRoute,
  AdminWebsiteHomepageRoute: AdminWebsiteHomepageRoute,
}

const AdminWebsiteRouteWithChildren = AdminWebsiteRoute._addFileChildren(
  AdminWebsiteRouteChildren,
)

interface AdminRouteChildren {
  AdminBranchesRoute: typeof AdminBranchesRouteWithChildren
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEmailSettingsRoute: typeof AdminEmailSettingsRoute
  AdminExceptionLogsRoute: typeof AdminExceptionLogsRoute
  AdminMenuRoute: typeof AdminMenuRouteWithChildren
  AdminMenusRoute: typeof AdminMenusRouteWithChildren
  AdminOrderStatusesRoute: typeof AdminOrderStatusesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWebsiteRoute: typeof AdminWebsiteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBranchesRoute: AdminBranchesRouteWithChildren,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEmailSettingsRoute: AdminEmailSettingsRoute,
  AdminExceptionLogsRoute: AdminExceptionLogsRoute,
  AdminMenuRoute: AdminMenuRouteWithChildren,
  AdminMenusRoute: AdminMenusRouteWithChildren,
  AdminOrderStatusesRoute: AdminOrderStatusesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWebsiteRoute: AdminWebsiteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MenuRouteChildren {
  MenuNameRoute: typeof MenuNameRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuNameRoute: MenuNameRoute,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LocationsRoute: LocationsRoute,
  MenuRoute: MenuRouteWithChildren,
  OffersRoute: OffersRoute,
  OrderTrackingRoute: OrderTrackingRoute,
  ReservationRoute: ReservationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
