// <auto-generated />
using HindIndisk.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HindIndisk.Web.Server.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710160000_AddHomeStorySectionSettings")]
    partial class AddHomeStorySectionSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
