// <auto-generated />
using System;
using HindIndisk.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HindIndisk.Web.Server.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707160000_AddClosureFields")]
    partial class AddClosureFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Full snapshot is maintained in ApplicationDbContextModelSnapshot.cs
        }
    }
}
